### ISSUE TITLE
Sidebar Nav menus do not show in pages generated by jekyll-archives

### ISSUE THREAD

**Issue by tillmanj** [tillmanj/eatingasturias#1]
The [Minimal Mistake Sidebar Navigation](https://mmistakes.github.io/minimal-mistakes/docs/layouts/#custom-sidebar-navigation-menu) does not show when included into pages built by the [jekyll-archives](https://github.com/jekyll/jekyll-archives) plugin.

For an example, look at the file: [archive-month.html](https://github.com/tillmanj/eatingasturias/blob/main/_layouts/archive-month.html)

## Tried So Far
- `author_profile: true` in the template frontmatter does trigger `{% include sidebar.html %}` as expected. See [sidebar.html](https://github.com/tillmanj/eatingasturias/blob/main/_includes/sidebar.html) for the relevant code.
- The default inclusion of the sidebar nav in the default layout section of `_config.yml` does not trigger inclusion:
```yaml
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      author: "Jon Tillman"
      author_url: "/about/jon/"
      toc: true
      toc_sticky: true
      sidebar:
        nav: [ recipes, culture, visit ]
```
- Setting the sidebar explicitly in the template frontmatter does no trigger inclusion:
```yaml
sidebar:
  nav: "recipes"
```
## Other Things I Have Checked
- my sidebar.html is identical to the minimal mistakes [file](https://github.com/mmistakes/minimal-mistakes/blob/4.26.2/_includes/sidebar.html)
- The [Archive Configuration](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings) page of the Minimal Mistakes documentation site points towards a potential for further investigation: "_To apply [Front Matter defaults](https://jekyllrb.com/docs/configuration/front-matter-defaults/) to pages generated by the jekyll-archives plugin, you can specify a scope of an empty path and a type of either tag or category._"
```yaml
defaults:
  - scope:
      path: ""
      type: tag
    values:
      author_profile: true
  - scope:
      path: ""
      type: category
    values:
      comments: false

```
